[package]
name = "sophon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7.0"
madvise = "0.1.0"
byte-unit = "4.0"
parking_lot = "0.11"
